# Generated by Django 2.2.5 on 2019-09-07 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyModel',
            fields=[
                ('sys_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=6, unique=True)),
                ('fid', models.CharField(max_length=6)),
                ('survey_title', models.CharField(max_length=100)),
                ('color_scheme', models.CharField(blank=True, max_length=10, null=True)),
                ('q_per_page', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('hit_count', models.BigIntegerField(blank=True, default=0)),
            ],
            options={
                'db_table': 'survey',
            },
        ),
        migrations.CreateModel(
            name='QuestionsModel',
            fields=[
                ('sys_id', models.AutoField(primary_key=True, serialize=False)),
                ('fid', models.CharField(max_length=6)),
                ('q_text', models.CharField(max_length=1024)),
                ('q_type', models.CharField(max_length=2)),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveyapp.SurveyModel')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='OptionsModel',
            fields=[
                ('sys_id', models.AutoField(primary_key=True, serialize=False)),
                ('fid', models.CharField(max_length=6)),
                ('q_text', models.CharField(max_length=1024)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveyapp.QuestionsModel')),
            ],
            options={
                'db_table': 'options',
            },
        ),
    ]
