# Generated by Django 2.2.5 on 2019-09-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveymodel',
            name='data',
            field=models.TextField(blank=True),
        ),
    ]
