# Generated by Django 2.2.5 on 2019-09-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0002_surveymodel_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsesModel',
            fields=[
                ('sys_id', models.AutoField(primary_key=True, serialize=False)),
                ('survey_id', models.IntegerField(blank=True)),
                ('q_id', models.IntegerField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'responses',
            },
        ),
        migrations.RenameField(
            model_name='surveymodel',
            old_name='survey_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='surveymodel',
            name='fid',
        ),
        migrations.AlterField(
            model_name='surveymodel',
            name='q_per_page',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
